### ISSUE TITLE
Sac:pixel figure

### ISSUE THREAD

**Issue by bycn** [denisyarats/pytorch_sac_ae#2]
What is the recommended way to recreate the sac:pixel from the results? Modify Pytorch_sac, or sac_ae, or is code available? (I know changes are trivial in some sense but I'd just like to keep the implementation as similar as possible)

**Comment by denisyarats** [comment]
You can set --decoder_update_freq to some large number, ideally larger than the total number of training steps. This will prevent decoder from being updated ever.

**Comment by bycn** [comment]
Thanks, appreciate it.
