### ISSUE TITLE
Code for running benchmarks on noisy observations

### ISSUE THREAD

**Issue by jarnefeltoliver** [denisyarats/pytorch_sac_ae#3]
I am interested in running benchmarks on noisy observations as described in section 5.2 of [https://arxiv.org/abs/1910.01741](url).
The code for this part would be greatly appreciated as it apparently is missing from the repo at the moment.

**Comment by denisyarats** [comment]
The environments that we used can be found here: https://github.com/facebookresearch/deep_bisim4control/blob/master/dmc2gym/wrappers.py#L103
