### ISSUE TITLE
tie encoders between actor and critic

### ISSUE THREAD

**Issue by xiangyyyy** [denisyarats/pytorch_sac_ae#4]
hello:
line 247 in sac_ae.py:self.actor.encoder.copy_conv_weights_from(self.critic.encoder) just copy parameters from critic encoder to actor encoder ,when you initialize sac agent. 
Why not synchronize the critic encoder parameters to the actor's encoder after each critic parameters update ?

**Comment by denisyarats** [comment]
copy_conv_weights not just copies parameters, it makes them sharable between the actor and critic.

**Comment by dvalenciar** [comment]
Hello, could you please explain why copy_conv_weights makes the weights sharable between the actor and critic during the whole training?

**Comment by ergo-zyh** [comment]
When I run the code, I found that the weights of the actor encoder doesn't change. So it's a bug line 342 in sac_ae.py: _, pi, log_pi, log_std = self.actor(obs, detach_encoder=True) should be log_pi, log_std = self.actor(obs).
The reason why this code can perform well is the environment and task is too simple, I guess.
